# Generated by Django 3.2.8 on 2021-12-04 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invest_word', models.CharField(max_length=100)),
                ('invest_defn', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_url', models.CharField(max_length=255)),
                ('news_snip', models.CharField(max_length=255)),
                ('news_date', models.DateField()),
                ('news_author', models.CharField(max_length=100)),
                ('news_img_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=30)),
                ('stock_ticker', models.CharField(max_length=30)),
                ('stock_description', models.CharField(max_length=100)),
                ('stock_pclose', models.FloatField()),
                ('stock_open', models.FloatField()),
                ('stock_bid', models.CharField(max_length=30)),
                ('stock_ask', models.CharField(max_length=30)),
                ('stock_volume', models.PositiveIntegerField(max_length=30)),
                ('stock_avgvolume', models.PositiveBigIntegerField(max_length=30)),
                ('stock_mcap', models.CharField(max_length=30)),
                ('submission_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User_pref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_stock_preferences', models.CharField(max_length=255)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.user')),
            ],
        ),
    ]
