# Generated by Django 3.2.8 on 2021-12-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_user_pref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_pref',
            name='stock',
        ),
        migrations.AddField(
            model_name='user_pref',
            name='user_stock_preferences',
            field=models.ManyToManyField(to='playground.Stocks'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='stock_avgvolume',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='stock_volume',
            field=models.PositiveIntegerField(),
        ),
    ]
