# Generated by Django 3.2.8 on 2021-11-19 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_dict_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_pref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.user')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.stocks')),
            ],
        ),
    ]
