# Generated by Django 3.2.8 on 2021-12-03 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_auto_20211203_0042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_pref',
        ),
    ]
