# Generated by Django 3.2.8 on 2021-12-04 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_user_pref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_pref',
            name='user_stock_preferences',
        ),
    ]
